INSERT INTO brand_product_domains (normalized_brand_name, domain)
VALUES
  ('COSRX', 'cosrx.com'),
  ('BEAUTY OF JOSEON', 'beautyofjoseon.com'),
  ('ANUA', 'anua.us'),
  ('SKIN1004', 'skin1004.com'),
  ('ROUND LAB', 'roundlab.com'),
  ('TORRIDEN', 'torriden.com'),
  ('ISNTREE', 'isntree.com'),
  ('HARUHARU WONDER', 'haruharuwonder.com'),
  ('PURITO SEOUL', 'purito.com'),
  ('PURITO', 'purito.com'),
  ('DEAR, KLAIRS', 'klairscosmetics.com'),
  ('KLAIRS', 'klairscosmetics.com'),
  ('SOME BY MI', 'somebymi.com'),
  ('IUNIK', 'iunik.com'),
  ('ETUDE', 'etude.com'),
  ('INNISFREE', 'innisfree.com'),
  ('LANEIGE', 'laneige.com'),
  ('SULWHASOO', 'sulwhasoo.com'),
  ('DR. JART', 'drjart.com'),
  ('DR. JART+', 'drjart.com'),
  ('MISSHA', 'misshaus.com'),
  ('THE FACE SHOP', 'thefaceshop.com'),
  ('BANILA CO', 'banila.com'),
  ('ROM&ND', 'romand.us'),
  ('TONYMOLY', 'tonymoly.us'),
  ('MEDIHEAL', 'medihealus.com'),
  ('MIXSOON', 'mixsoon.us'),
  ('ABIB', 'abib.com'),
  ('AXIS-Y', 'axis-y.com'),
  ('BENTON', 'bentoncosmetic.com'),
  ('NEOGEN', 'neogenlab.us'),
  ('PEACH & LILY', 'peachandlily.com'),
  ('AESTURA', 'aestura.com'),
  ('MEDICUBE', 'medicube.us'),
  ('TOCOBO', 'tocobo.us'),
  ('KRAVE BEAUTY', 'kravebeauty.com'),
  ('MA:NYO', 'manyo.us'),
  ('JUMISO', 'jumiso.com'),
  ('PYUNKANG YUL', 'pyunkangyulcom.com'),
  ('GLOW RECIPE', 'glowrecipe.com'),
  ('THE ORDINARY', 'theordinary.com'),
  ('CERAVE', 'cerave.com'),
  ('CETAPHIL', 'cetaphil.com'),
  ('NEUTROGENA', 'neutrogena.com'),
  ('AVEENO', 'aveeno.com'),
  ('EUCERIN', 'eucerin.com'),
  ('VANICREAM', 'vanicream.com'),
  ('PAULA''S CHOICE', 'paulaschoice.com'),
  ('SKINCEUTICALS', 'skinceuticals.com'),
  ('DERMALOGICA', 'dermalogica.com'),
  ('KIEHL''S', 'kiehls.com'),
  ('CLINIQUE', 'clinique.com'),
  ('ESTÉE LAUDER', 'esteelauder.com'),
  ('ESTEE LAUDER', 'esteelauder.com'),
  ('LANCÔME', 'lancome-usa.com'),
  ('LANCOME', 'lancome-usa.com'),
  ('SHISEIDO', 'shiseido.com'),
  ('TATCHA', 'tatcha.com'),
  ('DRUNK ELEPHANT', 'drunkelephant.com'),
  ('SUNDAY RILEY', 'sundayriley.com'),
  ('YOUTH TO THE PEOPLE', 'youthtothepeople.com'),
  ('FIRST AID BEAUTY', 'firstaidbeauty.com'),
  ('FARMACY', 'farmacybeauty.com'),
  ('BIOSSANCE', 'biossance.com'),
  ('SUPERGOOP!', 'supergoop.com'),
  ('SUPERGOOP', 'supergoop.com'),
  ('ELTAMD', 'eltamd.com'),
  ('TOWER 28', 'tower28beauty.com'),
  ('RARE BEAUTY', 'rarebeauty.com'),
  ('FENTY BEAUTY', 'fentybeauty.com'),
  ('NARS', 'narscosmetics.com'),
  ('MAC COSMETICS', 'maccosmetics.com'),
  ('M·A·C', 'maccosmetics.com'),
  ('CHARLOTTE TILBURY', 'charlottetilbury.com'),
  ('E.L.F. COSMETICS', 'elfcosmetics.com'),
  ('E.L.F.', 'elfcosmetics.com'),
  ('NYX PROFESSIONAL MAKEUP', 'nyxcosmetics.com'),
  ('NYX', 'nyxcosmetics.com'),
  ('MAYBELLINE', 'maybelline.com'),
  ('L''ORÉAL PARIS', 'lorealparisusa.com'),
  ('L''OREAL PARIS', 'lorealparisusa.com'),
  ('REVLON', 'revlon.com'),
  ('COVERGIRL', 'covergirl.com'),
  ('URBAN DECAY', 'urbandecay.com'),
  ('TOO FACED', 'toofaced.com'),
  ('BENEFIT COSMETICS', 'benefitcosmetics.com'),
  ('MAKE UP FOR EVER', 'makeupforever.com'),
  ('PAT MCGRATH LABS', 'patmcgrath.com'),
  ('MILK MAKEUP', 'milkmakeup.com'),
  ('SAIE', 'saiehello.com'),
  ('ILIA BEAUTY', 'iliabeauty.com'),
  ('ILIA', 'iliabeauty.com'),
  ('KOSAS', 'kosas.com'),
  ('MERIT', 'meritbeauty.com'),
  ('GLOSSIER', 'glossier.com'),
  ('RHODE', 'rhodeskin.com'),
  ('HAUS LABS', 'hauslabs.com'),
  ('HUDA BEAUTY', 'hudabeauty.com'),
  ('ANASTASIA BEVERLY HILLS', 'anastasiabeverlyhills.com'),
  ('BOBBI BROWN', 'bobbibrowncosmetics.com'),
  ('LAURA MERCIER', 'lauramercier.com'),
  ('SMASHBOX', 'smashbox.com'),
  ('BAREMINERALS', 'bareminerals.com'),
  ('SOL DE JANEIRO', 'soldejaneiro.com'),
  ('CAUDALIE', 'caudalie.com'),
  ('VICHY', 'vichyusa.com'),
  ('BIODERMA', 'bioderma.us'),
  ('AVÈNE', 'aveneusa.com'),
  ('AVENE', 'aveneusa.com'),
  ('THE INKEY LIST', 'theinkeylist.com'),
  ('NATURIUM', 'naturium.com'),
  ('BYOMA', 'byoma.com'),
  ('STRATIA', 'stratiaskin.com'),
  ('DIEUX', 'dieuxskin.com'),
  ('MURAD', 'murad.com'),
  ('ELEMIS', 'elemis.com')
ON CONFLICT (normalized_brand_name, domain) DO NOTHING;
